-- =====================================================
-- Feedback-Testdaten — Ruben Geyer (aus Forms-Excel 2024)
-- Idempotent: deterministische IDs + ON CONFLICT DO NOTHING.
-- Laeuft nur, wenn Rubens Athleten-Eintrag existiert. Entfernbar.
-- =====================================================
DO $$
DECLARE aid UUID;
BEGIN
  SELECT a.id INTO aid FROM athletes a JOIN auth.users u ON u.id=a.auth_user_id
   WHERE lower(u.email)='info@neue-weberei.de' LIMIT 1;
  IF aid IS NULL THEN RAISE NOTICE 'Ruben-Athlet nicht gefunden, skip'; RETURN; END IF;
  INSERT INTO feedback_entries (id, athlete_id, exercise_name, fehlerbild, handlungsanweisung, context, given_by, feedback_type, dartfish_url, helpful, r_technik, r_ausfuehrung, r_fortschritt, r_programm, r_wettkampf) VALUES
    (md5('fb-ruben-2024-0')::uuid, aid, 'Seitvorhebehalte rw.', 'Zackige Lenk Bewegungen unsicher  zu weit über dem Sattel geschoben', 'Mehr Druck auf den Lenker geben, nicht ganz so weit über den Sattel schieben', 'Lehrgang Albstadt', 'Lehrgangsleiter', 'verbale Korrektur nach der Übung', '', NULL, 2, 2, 2, 3, 2),
    (md5('fb-ruben-2024-1')::uuid, aid, 'Maute Sprung', 'Hart gelandet und nicht gestanden', 'Weicher springen und landen mehr setzen', 'Lehrgang Albstadt', 'Lehrgangsleiter', 'verbale Korrektur nach der Übung', '', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-2')::uuid, aid, 'Lenkerdrehung', 'Zu weit vorgedreht', 'Kürzer vordrehen', 'Heimtraining', 'ein anderer Sportler', 'verbale Korrektur nach der Übung', '', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-3')::uuid, aid, 'Drehsprung', 'Schwung geht verloren ab dem 2. Weil linkes Bein am Rahmen hängen bleibt', 'Beine länger zusammen lassen und zum Arm hin schwingen. Dann kompakt machen Lenker stehen lassen und dann Schwung  mitnehmen', 'Lehrgang Albstadt', 'Lehrgangsleiter', 'Video - einfache Analyse', '', 5, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-4')::uuid, aid, 'Maute Sprung', 'Rad kippt zu stark nach innen', 'Ich muss vor dem Springen kurz etwas gerader fahren', 'Lehrgang Albstadt', 'anderer Trainer', 'verbale Korrektur nach der Übung', '', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-5')::uuid, aid, 'Drehsprung', 'Hüfte dreht zu sehr auf und beim abdrücken pedalstellung bisschen zu früh', 'Länger warten beim Pedal & Hüfte verändern', 'Lehrgang Albstadt', 'Lehrgangsleiter', 'Video - einfache Analyse', '', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-6')::uuid, aid, 'Reitsitzsteiger rw ein Bein frh', 'Kreisbogen wird zu klein und Tempo geht verloren', 'etwas geringere Radschräglage und mehr Hüftknick am Beginn', 'Lehrgang Albstadt', 'Dieter Maute', 'Video - einfache Analyse', 'https://dartfi.sh/sddnqZaspz4', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-7')::uuid, aid, 'Drehsprung', 'Schwingen quer vor dem Rad', 'beim Abdruck linkes Bein zur Seite und Schultern weiter vor. Beie erst dann beim Schwingen schließen.', 'Lehrgang Albstadt', 'Dieter Maute', 'Video - einfache Analyse', 'https://dartfi.sh/Bv99sD4xSj1', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-8')::uuid, aid, 'Mautesprung', 'Zu starker Abdruck, Rad bleibt stehen und Lenker steht quer', 'Mehr setzen weniger springen', 'Lehrgang Albstadt', 'Lehrgangsleiter', 'verbale Korrektur nach der Übung', '', 5, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-9')::uuid, aid, 'Drehspung', 'Scheibenwischer und zu Wehmut Schultervorlage', 'Mehr Schultervorlage. Beginn der Übung nach einer halben Drehung beim stützen vor dem Rad. Hier muss eine kurze „Pause“ und Rad nicht zu mir herziehen -> loslassen', 'Lehrgang Albstadt', 'Lehrgangsleiter', 'Video - ausführliche Analyse (Video- Korrektur - Video 2)', '', 5, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-10')::uuid, aid, 'Rückwärtsserie', 'Tritt unrund -> wird es langsamer', 'Weniger mit Kraft runter treten dadurch automatisch mehr ziehen. Außerdem mehr Druck auf die rechte Po Backe -> Mehr Hüftknick und Brust raus', 'Lehrgang Albstadt', 'Lehrgangsleiter', 'verbale Korrektur nach der Übung', '', 4, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-11')::uuid, aid, 'Drehsprung', 'Querschwingen vor dem Rad', 'linkes Bein nicht so früh und aktiv zum rechten bein sondern verzögert ranschwingen lassen, Schulter weiter vor und loslassen also passiv schwingen lassen und nicht das Rad zum Körper herziehen, beim weitersppringen Beine mehr geschlossen lassen', 'Lehrgang Albstadt', 'Lehrgangsleiter', 'Video - ausführliche Analyse (Video- Korrektur - Video 2)', 'https://dartfi.sh/SuADjb9Hzq0', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-12')::uuid, aid, 'Maute Sprung', 'Zu viel Druck auf dem Sattel Kranz beim Aufgang. Dadurch zu wenig Druck auf Zehen -> Sattel stand nicht sauber', 'Vorne bleiben beim hochgehen und Druck auf Zehen spitzen.', 'Lehrgang Albstadt', 'Heimtrainer', 'verbale Korrektur nach der Übung', '', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-13')::uuid, aid, 'Drehsprung', 'Schwingt zu flach, Drehgeschwindigkeit beim Weiterpringen zu gering', 'Beim rausspringen linkes Bein zur Seite und nicht zum anderen Bein nach unten heranführen, gleichzeitig Schultern deutlich weiter vor, danach länger warten und Bein im Knie beugen und um den Arm gehen, dabei rechte Schulter nach vorne einfdrehen (möglichst kurz und kompakt machen), beim Drehen des Lenkers müssen die Schutern besser über dem Lenker bleiben.', 'Heimtraining', 'Dieter Maute', 'Video - einfache Analyse', 'https://dartfi.sh/GfaCK7AX1qd', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-14')::uuid, aid, 'Maute Sprung', 'Sattelstand kurz vor dem Sprung läuft nichtmehr so gut wie vorher', 'Kürzer anfahren und nicht auf einen Punkt festlegen wo ich springe sondern egal einspringen', 'Lehrgang Albstadt', 'Lehrgangsleiter', 'verbale Korrektur nach der Übung', '', NULL, 3, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-15')::uuid, aid, 'Drehspung', 'Bein geht senkrecht "Gestreckt" über Rahmen', 'Länger „warten“', 'Lehrgang Albstadt', 'Lehrgangsleiter', 'Video - ausführliche Analyse (Video- Korrektur - Video 2)', '', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-16')::uuid, aid, 'Drehsprung', 'Schwingt zu Rund, dadurch wenig Ausgleich durch Radlauf möglich', 'Schultern weiter vor, damit Körper mehr vor dem Rad hochwingt', 'Lehrgang Albstadt', 'Dieter Maute', 'Video - einfache Analyse', 'https://dartfi.sh/FEhJBB59mV8', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-17')::uuid, aid, 'Drehsprung', 'Weiterspringen nicht effektiv', 'linke Schulter beim Schwingen nach dem Rausspringen vorne lassen, warten und rechtes Bein nicht abspreizen, linkes Becken Richtung rechter Arm und dann Bein in Körperlinie ohne großes Abspreizen beigen und um Arm gehen', 'Lehrgang Albstadt', 'Dieter Maute', 'Video - einfache Analyse', 'https://dartfi.sh/zc3vQGVbgVc', NULL, NULL, NULL, NULL, NULL, NULL),
    (md5('fb-ruben-2024-18')::uuid, aid, 'Drehsprung', 'linke Schulter zu weit hinten, macht weiter wenn er vor dem Rad schwingt', 'Linke Schulter vorne lassen (zum Lenker ausgerichtet bleiben), Schwingen lassen und warten bis Körper Richtung Arm kommt', 'Lehrgang Albstadt', 'Dieter Maute', 'Video - einfache Analyse', 'https://dartfi.sh/vI8ahZqRlS4', NULL, NULL, NULL, NULL, NULL, NULL)
  ON CONFLICT (id) DO NOTHING;
END $$;
